Repository RAF-SI-2022/Banka-2-Frontend, pull requests merged in 2023-04, with the labels that each got.

#141 Add StockDetails Chart
  src/app/app.module.ts
  src/app/components/sprint2/buy-stock/buy-stock.component.html
  src/app/components/sprint2/buy-stock/buy-stock.component.ts
  src/app/components/sprint2/futures-component/futures.component.css
  src/app/components/sprint2/futures-component/futures.component.html
  src/app/components/sprint2/futures-component/futures.component.ts
  src/app/components/sprint2/stock-details/stock-details.component.html
  src/app/components/sprint2/stock-details/stock-details.component.ts
  src/app/components/sprint2/stocks/stocks.component.html
  src/app/components/sprint2/stocks/stocks.component.ts
  src/app/models/stock-exchange.model.ts
  src/app/services/stock.service.ts
  src/environments/environment.development.ts
  src/environments/environment.ts
Labels: size/L

#143 dodat forex
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/app/app.component.html
  src/app/components/sprint2/forex/forex.component.css
  src/app/components/sprint2/forex/forex.component.html
  src/app/components/sprint2/forex/forex.component.spec.ts
  src/app/components/sprint2/forex/forex.component.ts
  src/app/services/stock.service.ts
  src/assets/blogo.png
  src/assets/csv/filtered_forex_pairs.csv
  src/environments/environment.development.ts
  src/environments/environment.ts
Labels: size/XL

#144 Prepravljena validacija za buy i sell stock
  src/app/components/sprint2/buy-stock/buy-stock.component.html
  src/app/components/sprint2/buy-stock/buy-stock.component.ts
  src/app/components/sprint2/sell-stock/sell-stock.component.html
  src/app/components/sprint2/sell-stock/sell-stock.component.ts
  src/app/components/sprint2/stocks/stocks.component.ts
Labels: size/M

#145 adding futures integration
  src/app/components/app/app.component.ts
  src/app/components/sprint1/login/login.component.ts
  src/app/components/sprint1/profile/profile.component.html
  src/app/components/sprint2/futures-component/futures.component.css
  src/app/components/sprint2/futures-component/futures.component.html
  src/app/components/sprint2/futures-component/futures.component.ts
  src/app/components/sprint2/sell-stock/sell-stock.component.ts
  src/app/components/sprint2/single-future-table/single-future-table.component.css
  src/app/components/sprint2/single-future-table/single-future-table.component.html
  src/app/components/sprint2/single-future-table/single-future-table.component.ts
  src/app/components/sprint2/stocks/stocks.component.ts
  src/app/models/stock-exchange.model.ts
  src/app/services/stock.service.ts
  src/environments/environment.ts
Labels: size/XXL

#146 Add SellFutureComponent
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/app/app.component.html
  src/app/components/sprint1/home/home.component.html
  src/app/components/sprint2/forex/forex.component.css
  src/app/components/sprint2/forex/forex.component.html
  src/app/components/sprint2/forex/forex.component.ts
  src/app/components/sprint2/futures/buy-future-with-limit/buy-future-with-limit.component.css
  src/app/components/sprint2/futures/buy-future-with-limit/buy-future-with-limit.component.html
  src/app/components/sprint2/futures/buy-future-with-limit/buy-future-with-limit.component.ts
  src/app/components/sprint2/futures/futures-component/futures.component.css
  src/app/components/sprint2/futures/futures-component/futures.component.html
  src/app/components/sprint2/futures/futures-component/futures.component.ts
  src/app/components/sprint2/futures/sell-future-with-limit/sell-future-with-limit.component.css
  src/app/components/sprint2/futures/sell-future-with-limit/sell-future-with-limit.component.html
  src/app/components/sprint2/futures/sell-future-with-limit/sell-future-with-limit.component.ts
  src/app/components/sprint2/futures/sell-future/sell-future.component.css
  src/app/components/sprint2/futures/sell-future/sell-future.component.html
  src/app/components/sprint2/futures/sell-future/sell-future.component.ts
  src/app/components/sprint2/futures/single-future-table/single-future-table.component.css
  src/app/components/sprint2/futures/single-future-table/single-future-table.component.html
  src/app/components/sprint2/futures/single-future-table/single-future-table.component.ts
  src/app/components/sprint2/purchases/purchases.component.ts
  src/app/components/sprint2/single-future-table/single-future-table.component.ts
  src/app/components/sprint2/stocks/buy-stock/buy-stock.component.css
  src/app/components/sprint2/stocks/buy-stock/buy-stock.component.html
  src/app/components/sprint2/stocks/buy-stock/buy-stock.component.ts
  src/app/components/sprint2/stocks/sell-stock/sell-stock.component.css
  src/app/components/sprint2/stocks/sell-stock/sell-stock.component.html
  src/app/components/sprint2/stocks/sell-stock/sell-stock.component.ts
  src/app/components/sprint2/stocks/stock-details/stock-details.component.css
  src/app/components/sprint2/stocks/stock-details/stock-details.component.html
  src/app/components/sprint2/stocks/stock-details/stock-details.component.ts
  src/app/components/sprint2/stocks/stock-options/stock-options.component.css
  src/app/components/sprint2/stocks/stock-options/stock-options.component.html
  src/app/components/sprint2/stocks/stock-options/stock-options.component.ts
  src/app/components/sprint2/stocks/stocks-table/stocks.component.css
  src/app/components/sprint2/stocks/stocks-table/stocks.component.html
  src/app/components/sprint2/stocks/stocks-table/stocks.component.ts
  src/environments/environment.ts
Labels: size/XXL

#148 Sprint2
  src/app/components/sprint2/futures/buy-future-with-limit/buy-future-with-limit.component.html
  src/app/components/sprint2/futures/buy-future-with-limit/buy-future-with-limit.component.ts
  src/app/components/sprint2/futures/sell-future-with-limit/sell-future-with-limit.component.html
  src/app/components/sprint2/futures/sell-future-with-limit/sell-future-with-limit.component.ts
  src/app/components/sprint2/futures/sell-future/sell-future.component.ts
  src/app/components/sprint2/futures/single-future-table/single-future-table.component.html
  src/app/components/sprint2/futures/single-future-table/single-future-table.component.ts
  src/environments/environment.ts
Labels: size/L

#150 unapredjen forex
  src/app/components/sprint2/forex/forex.component.css
  src/app/components/sprint2/forex/forex.component.html
  src/app/components/sprint2/forex/forex.component.ts
  src/app/services/stock.service.ts
Labels: size/L

#149 Itegrate with back for futures
  src/app/components/app/app.component.html
  src/app/components/sprint2/futures/buy-future-with-limit/buy-future-with-limit.component.ts
  src/app/components/sprint2/futures/single-future-table/single-future-table.component.html
  src/app/components/sprint2/futures/single-future-table/single-future-table.component.ts
  src/app/services/stock.service.ts
Labels: size/L

#152 Sprint2
  src/app/components/app/app.component.html
  src/app/components/sprint2/forex/forex.component.html
  src/app/components/sprint2/stocks/stock-details/stock-details.component.css
  src/app/components/sprint2/stocks/stock-details/stock-details.component.html
  src/app/components/sprint2/stocks/stock-details/stock-details.component.ts
  src/app/components/sprint2/stocks/stocks-table/stocks.component.ts
  src/app/models/stock-exchange.model.ts
  src/app/services/stock.service.ts
  src/environments/environment.development.ts
  src/environments/environment.ts
Labels: size/L

#154 Fix AddUser
  src/app/components/sprint1/users/users.component.ts
  src/app/components/sprint2/stocks/stock-details/stock-details.component.css
  src/app/services/user-service.service.ts
Labels: size/S

#155 Futures dugmici i porudzbine izgled
  src/app/components/app/app.component.html
  src/app/components/sprint2/futures/single-future-table/single-future-table.component.html
  src/app/components/sprint2/purchases/purchases.component.html
  src/app/components/sprint2/purchases/purchases.component.ts
Labels: size/M

#156 izgleda dugmica na futures
  src/app/components/sprint2/futures/single-future-table/single-future-table.component.html
Labels: size/M

#157 dodat plusic na dugme
  src/app/components/sprint2/futures/single-future-table/single-future-table.component.html
Labels: size/XXL

#159 Sprint2
  src/app/components/sprint1/edit-user/edit-user.component.html
  src/app/components/sprint1/edit-user/edit-user.component.ts
  src/app/components/sprint1/users/users.component.ts
  src/app/components/sprint2/futures/sell-future-with-limit/sell-future-with-limit.component.ts
  src/app/components/sprint2/stocks/stock-details/stock-details.component.css
  src/app/components/sprint2/stocks/stock-details/stock-details.component.html
  src/app/services/user-service.service.ts
Labels: size/S

#160 resetovanje formi za buy i sell stock
  src/app/components/sprint2/stocks/buy-stock/buy-stock.component.html
  src/app/components/sprint2/stocks/buy-stock/buy-stock.component.ts
  src/app/components/sprint2/stocks/sell-stock/sell-stock.component.html
  src/app/components/sprint2/stocks/sell-stock/sell-stock.component.ts
Labels: size/S

#161 Needs new back to work
  src/app/components/sprint1/users/users.component.ts
  src/app/components/sprint2/forex/forex.component.html
  src/app/components/sprint2/stocks/buy-stock/buy-stock.component.html
  src/app/components/sprint2/stocks/sell-stock/sell-stock.component.html
  src/app/components/sprint2/stocks/stocks-table/stocks.component.html
  src/app/components/sprint2/stocks/stocks-table/stocks.component.ts
  src/app/models/stock-exchange.model.ts
  src/app/services/stock.service.ts
  src/app/services/user-service.service.ts
Labels: size/L

#163 Porudzbine povezane sa kupovinama Terminskih ugovora
  src/app/components/sprint2/futures/single-future-table/single-future-table.component.ts
  src/app/components/sprint2/purchases/purchases.component.html
  src/app/components/sprint2/purchases/purchases.component.ts
  src/app/components/sprint2/stocks/stocks-table/stocks.component.html
  src/app/models/stock-exchange.model.ts
  src/app/services/transactions-array.service.ts
Labels: size/L

#162 dodat folder directives i ubacena direktiva za validaciju da ne moze da se unese bilo sta sem brojeva u input za forex
  src/app/app.module.ts
  src/app/components/sprint2/forex/forex.component.html
  src/app/components/sprint2/forex/forex.component.ts
  src/app/directives/allow-numbers-only.directive.ts
Labels: size/S

#164 Sprint2
  src/app/components/sprint2/purchases/purchases.component.html
  src/app/components/sprint2/stocks/stocks-table/stocks.component.css
  src/app/components/sprint2/stocks/stocks-table/stocks.component.html
  src/app/components/sprint2/stocks/stocks-table/stocks.component.ts
Labels: size/M

#165 Add limit to user table and profile
  src/app/components/sprint1/profile/profile.component.html
  src/app/components/sprint1/users/users.component.html
  src/app/components/sprint2/forex/forex.component.css
  src/app/components/sprint2/forex/forex.component.html
  src/app/components/sprint2/stocks/stock-details/stock-details.component.ts
  src/app/components/sprint2/stocks/stocks-table/stocks.component.css
  src/app/models/users.model.ts
Labels: size/M

#166 Kraj sprinta2
  src/app/components/sprint2/stocks/buy-stock/buy-stock.component.ts
  src/app/components/sprint2/stocks/sell-stock/sell-stock.component.ts
  src/app/components/sprint2/stocks/stocks-table/stocks.component.html
  src/app/components/sprint2/stocks/stocks-table/stocks.component.ts
  src/app/services/stock.service.ts
Labels: size/L

#167 Porudzbine real-time prikaz
  src/app/components/sprint1/home/home.component.css
  src/app/components/sprint2/forex/forex.component.ts
  src/app/components/sprint2/futures/single-future-table/single-future-table.component.ts
Labels: size/M

#169 Futures prodaja real-time prikaz
  src/app/components/app/app.component.ts
  src/app/components/sprint1/home/home.component.html
  src/app/components/sprint2/futures/sell-future/sell-future.component.ts
Labels: size/S

#190 Add tabs and user limit
  src/app/app.module.ts
  src/app/components/sprint1/users/users.component.html
  src/app/components/sprint1/users/users.component.ts
  src/app/components/sprint2/stocks/stock-sell-table/stock-sell-table.component.css
  src/app/components/sprint2/stocks/stock-sell-table/stock-sell-table.component.html
  src/app/components/sprint2/stocks/stock-sell-table/stock-sell-table.component.ts
  src/app/components/sprint2/stocks/stocks-table/stocks.component.css
  src/app/components/sprint2/stocks/stocks-table/stocks.component.html
  src/app/components/sprint2/stocks/stocks-table/stocks.component.ts
  src/app/services/user-service.service.ts
Labels: size/L

#191 fix on nav bar and fix in future popup
  src/app/components/app/app.component.html
  src/app/components/app/app.component.ts
  src/app/components/sprint1/add-user/add-user.component.html
  src/app/components/sprint1/add-user/add-user.component.ts
  src/app/components/sprint2/futures/sell-future-with-limit/sell-future-with-limit.component.html
Labels: size/M

#194 Kapital: Dodtati tabovi i prvu tabelu
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/sprint2/purchases/purchases.component.html
  src/app/components/sprint3/capital/capital.component.css
  src/app/components/sprint3/capital/capital.component.html
  src/app/components/sprint3/capital/capital.component.ts
Labels: size/XL

#196 odradjen templeate
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/app/app.component.html
  src/app/components/sprint3/capital/capital.component.html
  src/app/components/sprint3/capital/capital.component.ts
  src/app/components/sprint3/future-contract/future-contract.component.css
  src/app/components/sprint3/future-contract/future-contract.component.html
  src/app/components/sprint3/future-contract/future-contract.component.ts
Labels: size/L

#197 Sprint3
  src/app/app.module.ts
  src/app/components/sprint3/capital/capital.component.html
  src/app/components/sprint3/capital/capital.component.ts
  src/app/components/sprint3/deposit-withdraw-capital/deposit-withdraw-capital.component.css
  src/app/components/sprint3/deposit-withdraw-capital/deposit-withdraw-capital.component.html
  src/app/components/sprint3/deposit-withdraw-capital/deposit-withdraw-capital.component.ts
  src/app/components/sprint3/transaction-list/transaction-list.component.css
  src/app/components/sprint3/transaction-list/transaction-list.component.html
  src/app/components/sprint3/transaction-list/transaction-list.component.ts
Labels: size/XL

#198 Prepravka tabela
  src/app/components/sprint2/purchases/purchases.component.html
  src/app/components/sprint3/capital/capital.component.html
  src/app/components/sprint3/capital/capital.component.ts
  src/app/components/sprint3/deposit-withdraw-capital/deposit-withdraw-capital.component.css
  src/app/components/sprint3/transaction-list/transaction-list.component.css
  src/app/components/sprint3/transaction-list/transaction-list.component.html
Labels: size/XXL

#200 dodate tabele neke razne
  src/app/components/sprint2/stocks/stock-sell-table/stock-sell-table.component.html
  src/app/components/sprint2/stocks/stock-sell-table/stock-sell-table.component.ts
  src/app/components/sprint3/capital/capital.component.html
  src/app/components/sprint3/future-contract/future-contract.component.html
  src/app/components/sprint3/future-contract/future-contract.component.ts
Labels: size/L

#202 Porudzbine povezane sa backendom
  src/app/components/sprint2/purchases/purchases.component.html
  src/app/components/sprint2/purchases/purchases.component.ts
  src/app/models/stock-exchange.model.ts
  src/app/services/stock.service.ts
Labels: size/M

#204 Sprint3
  src/app/components/sprint2/stocks/stock-sell-table/stock-sell-table.component.html
  src/app/components/sprint2/stocks/stock-sell-table/stock-sell-table.component.ts
  src/app/components/sprint3/future-contract/future-contract.component.ts
  src/app/services/stock.service.ts
Labels: size/L

#205 zatamni pozadinu kad se klikne na tabele, draggable=false, resizable=false
  src/app/components/sprint2/stocks/stock-sell-table/stock-sell-table.component.css
  src/app/components/sprint2/stocks/stock-sell-table/stock-sell-table.component.html
  src/app/components/sprint3/future-contract/future-contract.component.css
  src/app/components/sprint3/future-contract/future-contract.component.html
Labels: size/M

#207 Capital lista povezana sa backendom
  src/app/components/sprint3/capital/capital.component.html
  src/app/components/sprint3/capital/capital.component.ts
  src/app/components/sprint3/transaction-list/transaction-list.component.html
  src/app/components/sprint3/transaction-list/transaction-list.component.ts
  src/app/models/stock-exchange.model.ts
  src/app/services/stock.service.ts
Labels: size/L
