Repository RAF-SI-2022/Banka-2-Frontend, pull requests merged in 2023-03, with the labels that each got.

#11 First pull request -Filip
  README.md
Labels: size/XS, needs-ok-to-test

#12 Test2 branch
  README.md
Labels: size/XS, needs-ok-to-test

#13 treci pokusaj dodavanja brancha
  README.md
Labels: size/XS, needs-ok-to-test

#14 My first commit - testing pull request
  src/assets/markomiticproba.txt
Labels: size/XS, needs-ok-to-test

#18 dev branch test
  README.md
Labels: size/XS

#20 Kreirana login komponenta, dodati Bootstrap i PrimeNG
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/login-component/login-component.component.css
  src/app/login-component/login-component.component.html
  src/app/login-component/login-component.component.spec.ts
  src/app/login-component/login-component.component.ts
  src/main.ts
  tsconfig.app.json
  tsconfig.spec.json
Labels: size/XL, needs-ok-to-test

#22 Dodata forma za LoginComponent
  angular.json
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/login-component/login-component.component.html
  src/app/login-component/login-component.component.spec.ts
  src/app/login-component/login-component.component.ts
  src/app/login-component/login.component.ts
Labels: size/XXL, needs-ok-to-test

#23 users component
  src/app/app.module.ts
  src/app/users/users.component.css
  src/app/users/users.component.html
  src/app/users/users.component.spec.ts
  src/app/users/users.component.ts
Labels: size/M, needs-ok-to-test

#28 model i users
  src/app/app.module.ts
  src/app/components/models/users.model.ts
  src/app/components/users/users.component.html
  src/app/components/users/users.component.ts
Labels: needs-ok-to-test, size/L

#29 pipe za aktivity i popravka users stranice
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/app/app.component.html
  src/app/components/users/users.component.css
  src/app/components/users/users.component.html
  src/app/components/users/users.component.ts
  src/app/pipes/activity-pipe.pipe.spec.ts
  src/app/pipes/activity-pipe.pipe.ts
  src/app/services/user-service.service.spec.ts
Labels: needs-ok-to-test, size/L

#30 uradjen edit user
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/edit-user/edit-user.component.css
  src/app/components/edit-user/edit-user.component.html
  src/app/components/edit-user/edit-user.component.spec.ts
  src/app/components/edit-user/edit-user.component.ts
  src/app/model.ts
  src/app/services/user-service.service.ts
Labels: needs-ok-to-test, size/L

#31 Login skoro gotov
  src/app/components/login/login.component.css
  src/app/components/login/login.component.html
  src/app/components/login/login.component.ts
  src/app/components/models/auth.model.ts
  src/app/services/auth.service.spec.ts
  src/app/services/auth.service.ts
Labels: needs-ok-to-test, size/L

#32 skoro gotova users stranica cekamo bek i popup treba da se doda
  src/app/components/users/users.component.html
  src/app/components/users/users.component.ts
  src/app/services/user-service.service.ts
Labels: size/M, needs-ok-to-test

#33 uradjeni filteri
  src/app/app.module.ts
  src/app/components/users/users.component.html
  src/app/components/users/users.component.ts
Labels: size/L

#34 Edit User almost complete
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/add-user/add-user.component.css
  src/app/components/add-user/add-user.component.html
  src/app/components/add-user/add-user.component.spec.ts
  src/app/components/add-user/add-user.component.ts
  src/app/components/app/app.component.css
  src/app/components/app/app.component.html
  src/app/components/login/login.component.html
  src/app/components/login/login.component.ts
  src/app/components/users/users.component.css
  src/app/components/users/users.component.html
  src/app/components/users/users.component.ts
  src/index.html
Labels: size/L

#35 Sprint1
  README.md
Labels: size/XS

#36 Sprint1
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/app/app.component.html
  src/app/components/home/home.component.css
  src/app/components/home/home.component.html
  src/app/components/home/home.component.spec.ts
  src/app/components/home/home.component.ts
  src/app/components/login/login.component.html
  src/app/components/login/login.component.ts
  src/app/components/users/users.component.css
  src/app/components/users/users.component.html
  src/app/components/users/users.component.ts
  tsconfig.json
Labels: size/L

#37 Sprint1
  README.md
  cypress.config.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  package-lock.json
  package.json
  src/app/components/edit-user/edit-user.component.ts
  src/app/components/users/users.component.ts
  src/app/models/users.model.ts
  src/app/services/user-service.service.ts
Labels: size/XXL

#39 Toast, comments
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/app/app.component.ts
  src/app/components/login/login.component.html
  src/app/components/users/users.component.html
  src/app/components/users/users.component.ts
  src/app/pipes/activity-pipe.pipe.ts
  src/app/services/user-service.service.ts
Labels: size/L

#40 add user skoro zavrsen
  src/app/app.module.ts
  src/app/components/users/users.component.html
  src/app/components/users/users.component.ts
  src/app/models/users.model.ts
  src/app/pipes/activity-pipe.pipe.spec.ts
  src/app/services/user-service.service.ts
Labels: size/L

#41 Sprint1
  src/app/components/users/users.component.html
  src/app/components/users/users.component.ts
Labels: size/M

#43 uradjen dizajn za login page
  src/app/components/login/login.component.css
  src/app/components/login/login.component.html
  src/app/components/users/users.component.css
  src/assets/bk.png
  src/assets/fonts/Montserrat.ttf
  src/assets/img.png
Labels: size/L

#44 extracted modals into separate components
  src/app/app.module.ts
  src/app/components/add-user/add-user.component.css
  src/app/components/add-user/add-user.component.html
  src/app/components/add-user/add-user.component.spec.ts
  src/app/components/add-user/add-user.component.ts
  src/app/components/app/app.component.ts
  src/app/components/edit-user/edit-user.component.css
  src/app/components/edit-user/edit-user.component.html
  src/app/components/edit-user/edit-user.component.spec.ts
  src/app/components/edit-user/edit-user.component.ts
  src/app/components/login/login.component.ts
  src/app/components/users/users.component.html
  src/app/components/users/users.component.ts
Labels: size/XL

#45 update user almost done waithing for backend to fix bugs
  src/app/components/edit-user/edit-user.component.ts
  src/app/components/users/users.component.ts
  src/app/services/user-service.service.ts
Labels: size/M

#46 Some guards implemented, code cleanup
  src/app/app-routing.module.ts
  src/app/components/app/app.component.css
  src/app/components/app/app.component.html
  src/app/components/app/app.component.ts
  src/app/components/edit-user/edit-user.component.html
  src/app/components/edit-user/edit-user.component.ts
  src/app/components/login/login.component.html
  src/app/components/login/login.component.ts
  src/app/components/users/users.component.html
  src/app/components/users/users.component.ts
  src/app/guards/auth-guard/auth.guard.spec.ts
  src/app/guards/auth-guard/auth.guard.ts
  src/app/guards/login.guard.spec.ts
  src/app/guards/login.guard.ts
  src/app/model.ts
  src/app/models/users.model.ts
  src/app/services/user-service.service.ts
  src/index.html
Labels: size/L

#47 fixed guard
  src/app/app-routing.module.ts
  src/app/components/app/app.component.html
  src/app/guards/login.guard.ts
Labels: size/M

#50 Sprint1
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/app/app.component.html
  src/app/components/app/app.component.ts
  src/app/components/forgot-password/forgot-password.component.css
  src/app/components/forgot-password/forgot-password.component.html
  src/app/components/forgot-password/forgot-password.component.spec.ts
  src/app/components/forgot-password/forgot-password.component.ts
  src/app/components/login/login.component.html
  src/app/components/login/login.component.ts
  src/app/components/profile/profile.component.css
  src/app/components/profile/profile.component.html
  src/app/components/profile/profile.component.spec.ts
  src/app/components/profile/profile.component.ts
  src/app/services/user-service.service.ts
Labels: size/L

#49 izmenjen dizajn za search usera, izmenjeni button-i u tabeli
  package-lock.json
  package.json
  src/app/components/users/users.component.css
  src/app/components/users/users.component.html
  src/app/components/users/users.component.ts
Labels: size/L

#52 page not found component finished
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/app/app.component.html
  src/app/components/page-not-found/page-not-found.component.css
  src/app/components/page-not-found/page-not-found.component.html
  src/app/components/page-not-found/page-not-found.component.spec.ts
  src/app/components/page-not-found/page-not-found.component.ts
Labels: size/L

#54 Dodato editovanje profila i izmena sifre
  src/app/components/profile/profile.component.css
  src/app/components/profile/profile.component.html
  src/app/components/profile/profile.component.ts
Labels: size/L

#55 Popravljen README.md
  README.md
Labels: size/XS

#63 fixed buggs needs updated back to work
  src/app/app-routing.module.ts
  src/app/components/profile/profile.component.ts
  src/app/components/users/users.component.ts
  src/app/services/user-service.service.ts
Labels: size/L

#67 Pullovanje user permisija na loginu, tmp bug fix za logout dropdown
  src/app/components/app/app.component.html
  src/app/components/login/login.component.ts
  src/app/model.ts
  src/app/models/auth.model.ts
  src/app/services/user-service.service.ts
Labels: size/S

#70 dodat css na user tabelu
  package-lock.json
  package.json
  src/app/components/add-user/add-user.component.css
  src/app/components/app/app.component.ts
  src/app/components/edit-user/edit-user.component.css
  src/app/components/users/users.component.css
  src/app/components/users/users.component.html
  src/app/components/users/users.component.ts
  src/assets/icons/pen.png
Labels: size/XXL

#71 uradjen user profile
  src/app/components/profile/profile.component.css
  src/app/components/profile/profile.component.html
  src/app/components/users/users.component.html
  src/assets/icons/user.png
Labels: size/L

#72 Popravljen activate user
  src/app/components/users/users.component.html
  src/app/components/users/users.component.ts
  src/app/services/user-service.service.ts
Labels: size/XS

#74 CSS changes, filters, sidebar
  src/app/app.module.ts
  src/app/components/app/app.component.css
  src/app/components/app/app.component.html
  src/app/components/app/app.component.ts
  src/app/components/profile/profile.component.css
  src/app/components/profile/profile.component.html
  src/app/components/users/users.component.html
Labels: size/L

#76 job positions in forms
  src/app/components/add-user/add-user.component.ts
  src/app/components/edit-user/edit-user.component.ts
  src/app/components/login/login.component.html
  src/app/components/users/users.component.ts
Labels: size/M

#78 Validators, CSS, sidebar, forgor password page
  package-lock.json
  package.json
  src/app/components/add-user/add-user.component.ts
  src/app/components/app/app.component.css
  src/app/components/app/app.component.html
  src/app/components/app/app.component.ts
  src/app/components/edit-user/edit-user.component.ts
  src/app/components/forgot-password/forgot-password.component.css
  src/app/components/forgot-password/forgot-password.component.html
  src/app/components/forgot-password/forgot-password.component.ts
  src/app/components/home/home.component.html
  src/app/components/login/login.component.css
  src/app/components/login/login.component.html
  src/app/components/page-not-found/page-not-found.component.css
  src/app/components/page-not-found/page-not-found.component.html
  src/app/components/profile/profile.component.html
  src/app/components/profile/profile.component.ts
  src/app/components/users/users.component.css
  src/app/components/users/users.component.html
  src/assets/icons/forgot-image.svg
  src/assets/icons/person-circle.svg
Labels: size/L

#79 added dialog for not active users
  src/app/components/login/login.component.css
  src/app/components/login/login.component.html
  src/app/components/login/login.component.ts
  src/app/components/users/users.component.html
  src/app/components/users/users.component.ts
Labels: size/M

#81 Logo, language
  src/app/components/app/app.component.css
  src/app/components/app/app.component.html
  src/app/components/login/login.component.html
  src/assets/icons/blogo.png
  src/assets/icons/person-circle1.svg
Labels: size/M

#83 Authorisation
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/app/app.component.html
  src/app/components/app/app.component.ts
  src/app/components/login/login.component.html
  src/app/components/login/login.component.ts
  src/app/components/page-forbiden/page-forbiden.component.css
  src/app/components/page-forbiden/page-forbiden.component.html
  src/app/components/page-forbiden/page-forbiden.component.ts
  src/app/components/profile/profile.component.html
  src/app/components/profile/profile.component.ts
  src/app/guards/not.authorised.guard.ts
  src/app/guards/read-users-guard.guard.ts
Labels: size/L

#85 profile edit password bugfix
  src/app/components/profile/profile.component.ts
Labels: size/S

#87 dodat docker
  Dockerfile
  Makefile
  angular.json
  docker-compose.yml
  make.bat
Labels: size/M

#90 Sprint1
  README.md
Labels: size/XS

#89 Sprint1
  README.md
Labels: size/XS

#116 Small changes, preparation for sprint2 branch
  src/app/components/app/app.component.css
  src/app/components/app/app.component.html
  src/app/components/login/login.component.css
  src/app/components/login/login.component.html
  src/app/components/login/login.component.ts
  src/app/models/stock-exchange.model.ts
Labels: size/M

#117 Added models, stocks component
  README.md
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/app/app.component.html
  src/app/components/stocks/stocks.component.css
  src/app/components/stocks/stocks.component.html
  src/app/components/stocks/stocks.component.ts
  src/app/components/users/users.component.css
  src/app/models/stock-exchange.model.ts
Labels: size/XL

#118 Stock details added
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/sprint1/add-user/add-user.component.css
  src/app/components/sprint1/add-user/add-user.component.html
  src/app/components/sprint1/add-user/add-user.component.ts
  src/app/components/sprint1/change-password/change-password.component.css
  src/app/components/sprint1/change-password/change-password.component.html
  src/app/components/sprint1/change-password/change-password.component.spec.ts
  src/app/components/sprint1/change-password/change-password.component.ts
  src/app/components/sprint1/edit-user/edit-user.component.css
  src/app/components/sprint1/edit-user/edit-user.component.html
  src/app/components/sprint1/edit-user/edit-user.component.ts
  src/app/components/sprint1/forgot-password/forgot-password.component.css
  src/app/components/sprint1/forgot-password/forgot-password.component.html
  src/app/components/sprint1/forgot-password/forgot-password.component.ts
  src/app/components/sprint1/home/home.component.css
  src/app/components/sprint1/home/home.component.html
  src/app/components/sprint1/home/home.component.ts
  src/app/components/sprint1/login/login.component.css
  src/app/components/sprint1/login/login.component.html
  src/app/components/sprint1/login/login.component.ts
  src/app/components/sprint1/login/loginTestComponents.ts
  src/app/components/sprint1/page-forbiden/page-forbiden.component.css
  src/app/components/sprint1/page-forbiden/page-forbiden.component.html
  src/app/components/sprint1/page-forbiden/page-forbiden.component.ts
  src/app/components/sprint1/page-not-found/page-not-found.component.css
  src/app/components/sprint1/page-not-found/page-not-found.component.html
  src/app/components/sprint1/page-not-found/page-not-found.component.ts
  src/app/components/sprint1/profile/profile.component.css
  src/app/components/sprint1/profile/profile.component.html
  src/app/components/sprint1/profile/profile.component.ts
  src/app/components/sprint1/profile/profileTestComponents.ts
  src/app/components/sprint1/users/users.component.css
  src/app/components/sprint1/users/users.component.html
  src/app/components/sprint1/users/users.component.ts
  src/app/components/sprint1/users/usersTestComponents.ts
  src/app/components/sprint2/stock-details/stock-details.component.css
  src/app/components/sprint2/stock-details/stock-details.component.html
  src/app/components/sprint2/stock-details/stock-details.component.ts
  src/app/components/sprint2/stocks/stocks.component.css
  src/app/components/sprint2/stocks/stocks.component.html
  src/app/components/sprint2/stocks/stocks.component.ts
  src/app/components/stocks/stocks.component.ts
  src/app/guards/auth.guard.ts
  src/app/guards/login.guard.ts
  src/app/pipes/change-perc.pipe.ts
Labels: size/L

#119 added skeleton and buttons for options
  src/app/app.module.ts
  src/app/components/sprint1/login/login.component.css
  src/app/components/sprint2/stocks/stocks.component.css
  src/app/components/sprint2/stocks/stocks.component.html
  src/app/components/sprint2/stocks/stocks.component.ts
  src/app/guards/auth.guard.ts
  src/app/guards/login.guard.ts
Labels: size/M

#120 Chart
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/sprint1/login/login.component.css
  src/app/components/sprint2/stock-details/stock-details.component.html
  src/app/components/sprint2/stock-details/stock-details.component.ts
  src/app/components/sprint2/stocks/stocks.component.css
  src/app/components/sprint2/stocks/stocks.component.html
  src/app/components/sprint2/stocks/stocks.component.ts
Labels: size/L

#122 Cypress tests, graph fix
  angular.json
  cypress/e2e/testLogin.cy.js
  cypress/e2e/testProfile.cy.js
  cypress/e2e/testUsers.cy.js
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/app/app.component.ts
  src/app/components/sprint1/users/usersTestComponents.ts
  src/app/components/sprint2/stock-details/stock-details.component.css
  src/app/components/sprint2/stock-details/stock-details.component.html
  src/app/components/sprint2/stock-details/stock-details.component.ts
  src/app/components/sprint2/stocks/stocks.component.css
  src/app/components/sprint2/stocks/stocks.component.html
  src/app/components/sprint2/stocks/stocks.component.ts
  src/styles.css
Labels: size/XL

#125 ubacena stranica za BUY SELL
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/sprint2/buysell/buysell.component.css
  src/app/components/sprint2/buysell/buysell.component.html
  src/app/components/sprint2/buysell/buysell.component.spec.ts
  src/app/components/sprint2/buysell/buysell.component.ts
  src/app/models/stock-exchange.model.ts
Labels: size/L

#126 zavrsen BUY-SELL
  src/app/components/sprint2/buysell/buysell.component.css
  src/app/components/sprint2/buysell/buysell.component.html
  src/app/components/sprint2/buysell/buysell.component.ts
Labels: size/L

#127 Dodat confirmation za BUY-SELL
  src/app/components/sprint2/buysell/buysell.component.css
  src/app/components/sprint2/buysell/buysell.component.html
  src/app/components/sprint2/buysell/buysell.component.ts
Labels: size/M

#128 Stock details popup design
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/sprint2/buysell/buysell.component.css
  src/app/components/sprint2/buysell/buysell.component.html
  src/app/components/sprint2/buysell/buysell.component.spec.ts
  src/app/components/sprint2/buysell/buysell.component.ts
  src/app/components/sprint2/stock-details/stock-details.component.css
  src/app/components/sprint2/stock-details/stock-details.component.html
  src/app/components/sprint2/stock-details/stock-details.component.ts
  src/app/services/stock.service.ts
  src/environments/environment.development.ts
  src/environments/environment.ts
Labels: size/XL

#129 Almost done with stocks table
  src/app/app.module.ts
  src/app/components/sprint2/stocks/stocks.component.css
  src/app/components/sprint2/stocks/stocks.component.html
  src/app/components/sprint2/stocks/stocks.component.ts
  src/app/guards/auth.guard.ts
Labels: size/L

#130 Stock details graph buttons
  src/app/components/sprint2/stock-details/stock-details.component.css
  src/app/components/sprint2/stock-details/stock-details.component.html
  src/app/components/sprint2/stock-details/stock-details.component.ts
  src/app/components/sprint2/stocks/stocks.component.html
  src/app/components/sprint2/stocks/stocks.component.ts
Labels: size/M

#131 Design of table
  src/app/components/sprint2/stocks/stocks.component.html
  src/app/components/sprint2/stocks/stocks.component.ts
Labels: size/L

#133 Fixed hamburger bug
  src/app/components/app/app.component.ts
  src/app/components/sprint1/login/login.component.ts
  src/app/components/sprint2/stocks/stocks.component.ts
  src/app/models/stock-exchange.model.ts
  src/app/services/auth.service.ts
  src/app/services/user-service.service.ts
Labels: size/M

#135 user purchase history tabela (incomplete)
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/sprint2/purchases/purchases.component.css
  src/app/components/sprint2/purchases/purchases.component.html
  src/app/components/sprint2/purchases/purchases.component.spec.ts
  src/app/components/sprint2/purchases/purchases.component.ts
  src/app/models/stock-exchange.model.ts
Labels: size/XL

#136 Merge, stock options, details and other small fixes
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/app/app.component.css
  src/app/components/app/app.component.html
  src/app/components/app/app.component.ts
  src/app/components/sprint1/home/home.component.html
  src/app/components/sprint2/stock-details/stock-details.component.css
  src/app/components/sprint2/stock-details/stock-details.component.html
  src/app/components/sprint2/stock-details/stock-details.component.ts
  src/app/components/sprint2/stock-options/stock-options.component.css
  src/app/components/sprint2/stock-options/stock-options.component.html
  src/app/components/sprint2/stock-options/stock-options.component.ts
  src/app/components/sprint2/stocks/stocks.component.css
  src/app/components/sprint2/stocks/stocks.component.html
  src/app/services/auth.service.ts
Labels: size/XL

#137 Zavrsen Buy/Sell i Tabela sa porzdbinama korisnika
  src/app/components/sprint2/buysell/buysell.component.html
  src/app/components/sprint2/buysell/buysell.component.ts
  src/app/components/sprint2/purchases/purchases.component.html
  src/app/components/sprint2/purchases/purchases.component.ts
Labels: size/L

#138 Izgled sell/buy stocka
  src/app/app.module.ts
  src/app/components/sprint2/buy-stock/buy-stock.component.css
  src/app/components/sprint2/buy-stock/buy-stock.component.html
  src/app/components/sprint2/buy-stock/buy-stock.component.ts
  src/app/components/sprint2/purchases/purchases.component.spec.ts
  src/app/components/sprint2/sell-stock/sell-stock.component.css
  src/app/components/sprint2/sell-stock/sell-stock.component.html
  src/app/components/sprint2/sell-stock/sell-stock.component.ts
  src/app/components/sprint2/stocks/stocks.component.html
Labels: size/L

#139 Single future table and futures component and merge
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/app/app.component.css
  src/app/components/app/app.component.html
  src/app/components/sprint1/home/home.component.html
  src/app/components/sprint1/profile/profile.component.html
  src/app/components/sprint2/futures-component/futures.component.css
  src/app/components/sprint2/futures-component/futures.component.html
  src/app/components/sprint2/futures-component/futures.component.ts
  src/app/components/sprint2/single-future-table/single-future-table.component.css
  src/app/components/sprint2/single-future-table/single-future-table.component.html
  src/app/components/sprint2/single-future-table/single-future-table.component.ts
  src/app/components/sprint2/stock-details/stock-details.component.html
  src/app/components/sprint2/stock-details/stock-details.component.ts
  src/app/components/sprint2/stocks/stocks.component.ts
  src/app/models/stock-exchange.model.ts
  src/app/services/stock.service.ts
  src/assets/future_data.csv
  src/environments/environment.development.ts
  src/environments/environment.ts
Labels: size/XL

#140 Buy i sell stock popup-ovi
  src/app/components/sprint2/buy-stock/buy-stock.component.html
  src/app/components/sprint2/buy-stock/buy-stock.component.ts
  src/app/components/sprint2/sell-stock/sell-stock.component.html
  src/app/components/sprint2/sell-stock/sell-stock.component.ts
Labels: size/M
