Repository RAF-SI-2022/Banka-2-Frontend, pull requests merged in 2023-06, with the labels that each got.

#250 Uradjen Kontakt za kompanije
  src/app/app.module.ts
  src/app/components/sprint4/company-details/company-details.component.html
  src/app/components/sprint4/company-details/company-details.component.ts
  src/app/components/sprint4/create-company-contact/create-company-contact.component.css
  src/app/components/sprint4/create-company-contact/create-company-contact.component.html
  src/app/components/sprint4/create-company-contact/create-company-contact.component.ts
  src/app/components/sprint4/single-contact/single-contact.component.css
  src/app/components/sprint4/single-contact/single-contact.component.html
  src/app/components/sprint4/single-contact/single-contact.component.ts
Labels: size/L

#251 Sprint4
  src/app/components/sprint4/companies/companies.component.html
  src/app/components/sprint4/companies/companies.component.ts
  src/app/components/sprint4/company-details/company-details.component.html
  src/app/components/sprint4/company-details/company-details.component.ts
  src/app/components/sprint4/create-company-account/create-company-account.component.html
  src/app/components/sprint4/create-company-account/create-company-account.component.ts
  src/app/components/sprint4/create-company-contact/create-company-contact.component.ts
  src/app/components/sprint4/create-company-contract/create-company-contract.component.ts
  src/app/components/sprint4/create-company/create-company.component.html
  src/app/components/sprint4/create-company/create-company.component.ts
  src/app/components/sprint4/single-account/single-account.component.ts
  src/app/components/sprint4/single-contact/single-contact.component.ts
  src/app/components/sprint4/single-contract/single-contract.component.css
  src/app/components/sprint4/single-contract/single-contract.component.html
  src/app/components/sprint4/single-contract/single-contract.component.ts
  src/app/models/stock-exchange.model.ts
  src/app/services/company.service.ts
  src/app/services/contract.service.ts
  src/app/services/otc.service.ts
Labels: size/XL

#252 fix for change company, create company and put values and template
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/newSpec/register/register.component.css
  src/app/components/newSpec/register/register.component.html
  src/app/components/newSpec/register/register.component.ts
  src/app/components/sprint4/company-details/company-details.component.html
  src/app/components/sprint4/company-details/company-details.component.ts
  src/app/services/company.service.ts
Labels: size/XL

#254 Dodaj Ugovor, Dodaj Kontakt
  src/app/components/sprint4/company-details/company-details.component.html
  src/app/components/sprint4/company-details/company-details.component.ts
  src/app/components/sprint4/create-company-contact/create-company-contact.component.html
  src/app/components/sprint4/create-company-contact/create-company-contact.component.ts
  src/app/components/sprint4/create-company-contract/create-company-contract.component.ts
  src/app/components/sprint4/single-contact/single-contact.component.html
  src/app/components/sprint4/single-contact/single-contact.component.ts
  src/app/models/stock-exchange.model.ts
  src/app/services/otc.service.ts
Labels: size/L

#255 Fix mali
  src/app/components/sprint4/company-details/company-details.component.ts
Labels: size/XS

#256 Sprint4
  src/app/components/sprint4/companies/companies.component.html
  src/app/components/sprint4/company-details/company-details.component.html
  src/app/components/sprint4/company-details/company-details.component.ts
  src/app/components/sprint4/create-company-account/create-company-account.component.html
  src/app/components/sprint4/create-company-account/create-company-account.component.ts
  src/app/components/sprint4/create-company-contact/create-company-contact.component.ts
  src/app/components/sprint4/create-company-contract/create-company-contract.component.ts
  src/app/components/sprint4/single-account/single-account.component.html
  src/app/components/sprint4/single-account/single-account.component.ts
  src/app/components/sprint4/single-contact/single-contact.component.ts
  src/app/models/stock-exchange.model.ts
  src/app/services/company.service.ts
Labels: size/XL

#268 otc komponenta dodata
  src/app/components/sprint4/companies/companies.component.html
  src/app/components/sprint4/companies/companies.component.ts
  src/app/components/sprint4/single-contract/single-contract.component.html
  src/app/components/sprint4/transaction-element-creation/transaction-element-creation.component.css
  src/app/components/sprint4/transaction-element-creation/transaction-element-creation.component.html
  src/app/components/sprint4/transaction-element-creation/transaction-element-creation.component.ts
Labels: size/M

#269 Kontakt svi bagovi fixovani
  src/app/components/sprint4/company-details/company-details.component.ts
Labels: size/S

#270 template za element component i css
  src/app/components/sprint4/transaction-element-creation/transaction-element-creation.component.css
  src/app/components/sprint4/transaction-element-creation/transaction-element-creation.component.html
  src/app/components/sprint4/transaction-element-creation/transaction-element-creation.component.spec.ts
  src/app/components/sprint4/transaction-element-creation/transaction-element-creation.component.ts
Labels: size/L

#271 dodato za srkija
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/sprint2/stocks/stock-options/stock-options.component.html
  src/app/components/sprint2/stocks/stock-options/stock-options.component.ts
  src/app/components/sprint2/stocks/stock-sell-table/stock-sell-table.component.html
  src/app/components/sprint2/stocks/stock-sell-table/stock-sell-table.component.ts
  src/app/components/sprint2/stocks/stocks-table/stocks.component.html
  src/app/components/sprint2/stocks/stocks-table/stocks.component.ts
  src/app/components/sprint3/my-stock-options/my-stock-options.component.html
  src/app/components/sprint3/my-stock-options/my-stock-options.component.ts
  src/styles.css
Labels: size/L

#273 Sprint4
  src/app/components/sprint2/stocks/stock-sell-table/stock-sell-table.component.ts
  src/app/components/sprint3/my-stock-options/my-stock-options.component.ts
  src/app/components/sprint4/single-contract/single-contract.component.ts
  src/app/components/sprint4/transaction-element-creation/transaction-element-creation.component.html
  src/app/components/sprint4/transaction-element-creation/transaction-element-creation.component.ts
  src/app/services/stock.service.ts
Labels: size/L

#275 TransactionElement
  src/app/components/sprint4/transaction-element-creation/transaction-element-creation.component.html
  src/app/components/sprint4/transaction-element-creation/transaction-element-creation.component.ts
Labels: size/M

#276 companies fix and login fix
  src/app/components/sprint1/login/login.component.css
  src/app/components/sprint4/companies/companies.component.html
Labels: size/S

#277 dodat container za heading i svi headings od recievedElement
  src/app/components/sprint4/transaction-element-creation/transaction-element-creation.component.html
  src/app/components/sprint4/transaction-element-creation/transaction-element-creation.component.ts
Labels: size/S

#281 Changes to OTC buying
  src/app/components/sprint2/stocks/stock-options/stock-options.component.css
  src/app/components/sprint2/stocks/stock-options/stock-options.component.html
  src/app/components/sprint3/my-stock-options/my-stock-options.component.css
  src/app/components/sprint4/single-contract/single-contract.component.ts
  src/app/components/sprint4/transaction-element-creation/transaction-element-creation.component.ts
Labels: size/L

#283 Sprint4
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/sprint4/company-details/company-details.component.ts
  src/app/components/sprint4/single-contract/single-contract.component.html
  src/app/components/sprint4/single-contract/single-contract.component.ts
Labels: size/XXL

#288 Sprint4-ReRouted
  src/app/components/app/app.component.html
  src/app/components/sprint1/home/home.component.css
  src/app/components/sprint4/single-contract/single-contract.component.ts
  src/app/services/auth.service.ts
  src/app/services/company.service.ts
  src/app/services/otc.service.ts
  src/app/services/stock.service.ts
  src/app/services/user-service.service.ts
  src/assets/home-final-01.png
  src/environments/environment.development.ts
  src/environments/environment.ts
Labels: size/L

#289 Create element validation
  src/app/components/sprint4/transaction-element-creation/transaction-element-creation.component.html
  src/app/components/sprint4/transaction-element-creation/transaction-element-creation.component.ts
Labels: size/M

#291 Marzni racun
  src/app/components/sprint3/capital/capital.component.html
  src/app/components/sprint3/capital/capital.component.ts
  src/app/components/sprint3/margin-transaction-list/margin-transaction-list.component.html
  src/app/components/sprint3/margin-transaction-list/margin-transaction-list.component.ts
  src/app/models/stock-exchange.model.ts
  src/app/services/stock.service.ts
Labels: size/L

#295 Sprint 5
  .prow/prod-postsubmits.yaml
  .prow/test-presubmits.yaml
  angular.json
  docker/frontend.Dockerfile
  kubernetes/Chart.yaml
  kubernetes/templates/flyway-baseline.yaml
  kubernetes/templates/ingress.yaml
  kubernetes/templates/main.yaml
  kubernetes/templates/mongo.yaml
  kubernetes/templates/otc.yaml
  kubernetes/templates/redis.yaml
  kubernetes/templates/relational.yaml
  kubernetes/templates/users.yaml
  kubernetes/values.yaml
  src/environments/environment.ts
Labels: size/XL

#296 Dev
  .prow/prod-postsubmits.yaml
  .prow/test-presubmits.yaml
  angular.json
  docker/frontend.Dockerfile
  kubernetes/Chart.yaml
  kubernetes/templates/flyway-baseline.yaml
  kubernetes/templates/ingress.yaml
  kubernetes/templates/main.yaml
  kubernetes/templates/mongo.yaml
  kubernetes/templates/otc.yaml
  kubernetes/templates/redis.yaml
  kubernetes/templates/relational.yaml
  kubernetes/templates/users.yaml
  kubernetes/values.yaml
  src/environments/environment.ts
Labels: size/XL

#299 racuni, dodavanje racuna, styles
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/app/app.component.html
  src/app/components/sprint5/add-account/add-account.component.css
  src/app/components/sprint5/add-account/add-account.component.html
  src/app/components/sprint5/add-account/add-account.component.ts
  src/app/components/sprint5/balance/balance.component.css
  src/app/components/sprint5/balance/balance.component.html
  src/app/components/sprint5/balance/balance.component.ts
Labels: size/XL

#300 Sprint5
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/create-local-user-account/create-user-account.component.css
  src/app/components/create-local-user-account/create-user-account.component.html
  src/app/components/create-local-user-account/create-user-account.component.spec.ts
  src/app/components/create-local-user-account/create-user-account.component.ts
  src/app/components/sprint2/stocks/stock-options/stock-options.component.html
  src/app/components/sprint4/create-company-contact/create-company-contact.component.ts
Labels: size/XL

#301 routing na dodavanje racuna
  src/app/components/sprint5/balance/balance.component.html
  src/app/components/sprint5/balance/balance.component.ts
  src/environments/environment.development.ts
  src/environments/environment.ts
Labels: size/M

#303 Sprint5
  src/app/app.module.ts
  src/app/components/create-local-user-account/create-user-account.component.css
  src/app/components/create-local-user-account/create-user-account.component.html
  src/app/components/create-local-user-account/create-user-account.component.ts
  src/app/components/sprint3/capital/capital.component.html
  src/app/components/sprint3/capital/capital.component.ts
  src/app/components/sprint3/margin-transaction-list/margin-transaction-list.component.html
  src/app/components/sprint3/margin-transaction-list/margin-transaction-list.component.ts
  src/app/components/sprint5/balance/balance.component.html
  src/app/components/stepper-test/stepper-test.component.css
  src/app/components/stepper-test/stepper-test.component.html
  src/app/components/stepper-test/stepper-test.component.spec.ts
  src/app/components/stepper-test/stepper-test.component.ts
  src/app/models/stock-exchange.model.ts
  src/app/services/stock.service.ts
Labels: size/XXL

#304 payments komponenta
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/app/app.component.html
  src/app/components/sprint5/balance/balance.component.html
  src/app/components/sprint5/payments/payments.component.css
  src/app/components/sprint5/payments/payments.component.html
  src/app/components/sprint5/payments/payments.component.ts
  src/app/guards/auth.guard.ts
Labels: size/L

#305 payments -> transaction payment added
  src/app/components/sprint5/payments/payments.component.css
  src/app/components/sprint5/payments/payments.component.html
  src/app/components/sprint5/payments/payments.component.ts
Labels: size/M

#306 Replace old add user account
  src/app/app.module.ts
  src/app/components/add-user-account/add-user-account.component.css
  src/app/components/add-user-account/add-user-account.component.html
  src/app/components/add-user-account/add-user-account.component.spec.ts
  src/app/components/add-user-account/add-user-account.component.ts
  src/app/components/sprint5/balance/balance.component.html
  src/app/components/sprint5/balance/balance.component.ts
Labels: size/M

#307 payments->PAYMENT_RECIPIENTS. (dodavanje primaoca, brisanje, pregled, izmena)
  src/app/components/sprint5/payments/payments.component.css
  src/app/components/sprint5/payments/payments.component.html
  src/app/components/sprint5/payments/payments.component.ts
Labels: size/L

#308 promenjena auth ruta
  src/app/services/auth.service.ts
Labels: size/XS

#310 Add Account fully integrated with back
  src/app/components/add-user-account/add-user-account.component.css
  src/app/components/add-user-account/add-user-account.component.html
  src/app/components/add-user-account/add-user-account.component.ts
  src/app/components/sprint5/balance/balance.component.css
  src/app/components/sprint5/balance/balance.component.html
  src/app/components/sprint5/balance/balance.component.ts
  src/app/models/client.model.ts
  src/app/services/client.service.ts
Labels: size/XL

#313 Small changes
  src/app/components/app/app.component.ts
  src/app/components/newSpec/register/register.component.html
  src/app/components/newSpec/register/register.component.ts
Labels: size/S

#315 Sprint5
  src/app/app-routing.module.ts
  src/app/components/app/app.component.html
  src/app/components/app/app.component.ts
  src/app/components/newSpec/register/register.component.ts
  src/app/components/sprint1/home/home.component.html
  src/app/components/sprint1/home/home.component.ts
  src/app/components/sprint5/balance/balance.component.ts
  src/app/components/sprint5/payments/payments.component.html
  src/app/guards/client-only.guard.ts
  src/app/guards/client.guard.ts
  src/app/services/client.service.ts
  src/app/services/user-service.service.ts
Labels: size/L

#318 payments and stuff
  src/app/components/newSpec/register/register.component.ts
  src/app/components/sprint5/payments/payments.component.css
  src/app/components/sprint5/payments/payments.component.html
  src/app/components/sprint5/payments/payments.component.ts
  src/app/models/client.model.ts
  src/app/services/client.service.ts
  src/app/services/user-service.service.ts
Labels: size/XL

#319 Small CSS changes, mrdz sa Ilijom
  src/app/components/sprint5/payments/payments.component.css
  src/app/components/sprint5/payments/payments.component.html
Labels: size/M

#320 Small change with payments
  src/app/components/sprint5/payments/payments.component.html
  src/app/components/sprint5/payments/payments.component.ts
Labels: size/M

#321 transakcije uradjene
  src/app/components/sprint5/payments/payments.component.html
  src/app/components/sprint5/payments/payments.component.ts
  src/app/models/client.model.ts
  src/app/services/client.service.ts
Labels: lgtm, approved, size/L

#322 dodat prokleti autocomplete sa buttonom za new payment, dodavanje recipients-a...
  src/app/app.module.ts
  src/app/components/sprint5/payments/payments.component.css
  src/app/components/sprint5/payments/payments.component.html
  src/app/components/sprint5/payments/payments.component.ts
  src/app/models/client.model.ts
  src/app/services/client.service.ts
Labels: lgtm, approved, size/L

#324 CI/CD sync with back
  .prow/dev-presubmits.yaml
  .prow/prod-postsubmits.yaml
Labels: size/M

#325 edit recipients, validacija na frontu
  src/app/components/sprint5/payments/payments.component.ts
  src/app/services/client.service.ts
Labels: size/M

#328 payments done
  src/app/components/sprint5/payments/payments.component.css
  src/app/components/sprint5/payments/payments.component.html
  src/app/components/sprint5/payments/payments.component.ts
  src/app/models/client.model.ts
  src/app/services/client.service.ts
Labels: size/L

#329 I must explain to you how all this mistaken idea of denouncing pl…
  src/app/components/sprint5/payments/payments.component.html
  src/app/components/sprint5/payments/payments.component.ts
  src/app/models/client.model.ts
Labels: size/M

#330 fix for guard and added buttons to logins to migrate
  src/app/app-routing.module.ts
  src/app/components/newSpec/register/register.component.css
  src/app/components/newSpec/register/register.component.html
  src/app/components/sprint1/login/login.component.css
  src/app/components/sprint1/login/login.component.html
  src/app/components/sprint5/balance/balance.component.css
  src/app/components/sprint5/user-balance/user-balance.component.html
Labels: size/M

#340 ok
  src/app/components/sprint5/balance/balance.component.html
  src/app/components/sprint5/payments/payments.component.html
  src/app/components/sprint5/payments/payments.component.ts
  src/app/models/client.model.ts
  src/app/services/client.service.ts
Labels: size/L

#341 Sprint5
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/app/app.component.html
  src/app/components/sprint5/loan/loan.component.css
  src/app/components/sprint5/loan/loan.component.html
  src/app/components/sprint5/loan/loan.component.spec.ts
  src/app/components/sprint5/loan/loan.component.ts
  src/app/models/client.model.ts
  src/app/services/client.service.ts
Labels: size/XL

#342 Zavrseni detalji racuna
  src/app/app.module.ts
  src/app/components/sprint5/balance/balance.component.html
  src/app/components/sprint5/balance/balance.component.ts
  src/app/components/sprint5/single-user-balance/single-user-balance.component.css
  src/app/components/sprint5/single-user-balance/single-user-balance.component.html
  src/app/components/sprint5/single-user-balance/single-user-balance.component.ts
  src/app/components/sprint5/user-balance/user-balance.component.html
  src/app/components/sprint5/user-balance/user-balance.component.ts
  src/app/services/client.service.ts
Labels: size/L

#346 client login token za remember sada radi i popravljen poziv metode ch…
  src/app/components/app/app.component.html
  src/app/components/newSpec/register/register.component.ts
Labels: size/XS

#354 Fix Dockerfiles sed command
  OWNERS
  docker/frontend-dev.Dockerfile
  docker/frontend-prod.Dockerfile
Labels: priority/urgent, size/S

#353 Change response type in denyLoanRequest method
  src/app/services/client.service.ts
Labels: size/XS

#355 Fix Dockerfile sed command for line 13
  docker/frontend-dev.Dockerfile
  docker/frontend-prod.Dockerfile
Labels: size/XS, lgtm, approved

#356 Fix Dockerfiles try_files directive
  docker/frontend-dev.Dockerfile
  docker/frontend-prod.Dockerfile
Labels: size/S

#359 Mali bugfixes
  src/app/components/sprint1/users/users.component.html
  src/app/components/sprint1/users/users.component.ts
  src/app/components/sprint3/capital/capital.component.html
Labels: approved

#360 Devizni racun valute fix
  src/app/components/sprint5/add-user-account/add-user-account.component.ts
Labels: approved

#361 Account Radio Buttons
  src/app/components/sprint5/add-user-account/add-user-account.component.html
Labels: size/XS, approved

#362 prikazuju se krediti korisnikovi sada.
  src/app/components/sprint5/loan/loan.component.html
  src/app/components/sprint5/loan/loan.component.ts
  src/app/services/client.service.ts
Labels: approved, size/M

#363 loan-details.component.html napravljen ali iz neko razloga metoda open() cita kao undefined - kao da ne moze naci metodu??? approve-loan-request.component.html je tek in progress za sada je sve hardcode
  src/app/app.module.ts
  src/app/components/sprint5/approve-loan-request/approve-loan-request.component.css
  src/app/components/sprint5/approve-loan-request/approve-loan-request.component.html
  src/app/components/sprint5/approve-loan-request/approve-loan-request.component.ts
  src/app/components/sprint5/loan-details/loan-details.component.css
  src/app/components/sprint5/loan-details/loan-details.component.html
  src/app/components/sprint5/loan-details/loan-details.component.ts
  src/app/components/sprint5/loan/loan.component.html
  src/app/components/sprint5/loan/loan.component.ts
Labels: approved

#364 Added reset otp form after submit. The Kubernetes test crash may have been impacted by this. Author: Ilija D.
  src/app/components/sprint5/payments/payments.component.ts
Labels: size/XS

#365 login-details-component.html sada radiiiiiiiiiiiii
  src/app/components/sprint5/loan-details/loan-details.component.ts
  src/app/components/sprint5/loan/loan.component.html
  src/app/components/sprint5/loan/loan.component.ts
  src/app/components/sprint5/request-loan/request-loan.component.html
  src/app/components/sprint5/request-loan/request-loan.component.ts
Labels: approved, size/M

#366 placanje rate kredita
  src/app/components/sprint5/loan/loan.component.html
  src/app/components/sprint5/loan/loan.component.ts
  src/app/services/client.service.ts
Labels: size/M

#367 Sprint5 - jebite se krediti vise breeeeeee
  src/app/components/sprint5/approve-loan-request/approve-loan-request.component.html
  src/app/components/sprint5/approve-loan-request/approve-loan-request.component.ts
  src/app/components/sprint5/loan/loan.component.html
  src/app/components/sprint5/loan/loan.component.ts
  src/app/components/sprint5/payments/payments.component.html
  src/app/components/sprint5/request-loan/request-loan.component.html
  src/app/components/sprint5/request-loan/request-loan.component.ts
  src/app/services/client.service.ts
Labels: approved, size/L

#370 Krediti umrite.
  src/app/components/sprint5/approve-loan-request/approve-loan-request.component.html
  src/app/components/sprint5/approve-loan-request/approve-loan-request.component.ts
  src/app/components/sprint5/loan-details/loan-details.component.html
  src/app/components/sprint5/loan/loan.component.html
  src/app/services/client.service.ts
Labels: approved, size/M

#371 ucitavanje rata
  src/app/components/sprint5/loan/loan.component.html
  src/app/components/sprint5/loan/loan.component.ts
  src/app/services/client.service.ts
Labels: size/M

#372 Funkcionalno gotovi krediti
  src/app/components/sprint5/loan/loan.component.html
  src/app/components/sprint5/loan/loan.component.ts
Labels: approved, size/M

#374 rute fix
  src/app/components/sprint5/approve-loan-request/approve-loan-request.component.html
  src/app/components/sprint5/approve-loan-request/approve-loan-request.component.ts
  src/app/services/stock.service.ts
Labels: approved

#373 Dopunjen CI/CD
  .prow/branch-verify.yaml
  .prow/snyk-verify.yaml
Labels: size/M

#375 Sprint5
  .prow/branch-verify.yaml
  .prow/snyk-verify.yaml
  src/app/app.module.ts
  src/app/components/sprint1/users/users.component.html
  src/app/components/sprint1/users/users.component.ts
  src/app/components/sprint3/capital/capital.component.html
  src/app/components/sprint5/add-user-account/add-user-account.component.html
  src/app/components/sprint5/add-user-account/add-user-account.component.ts
  src/app/components/sprint5/approve-loan-request/approve-loan-request.component.css
  src/app/components/sprint5/approve-loan-request/approve-loan-request.component.html
  src/app/components/sprint5/approve-loan-request/approve-loan-request.component.ts
  src/app/components/sprint5/loan-details/loan-details.component.css
  src/app/components/sprint5/loan-details/loan-details.component.html
  src/app/components/sprint5/loan-details/loan-details.component.ts
  src/app/components/sprint5/loan/loan.component.html
  src/app/components/sprint5/loan/loan.component.ts
  src/app/components/sprint5/payments/payments.component.html
  src/app/components/sprint5/payments/payments.component.ts
  src/app/components/sprint5/request-loan/request-loan.component.html
  src/app/components/sprint5/request-loan/request-loan.component.ts
  src/app/services/client.service.ts
  src/app/services/stock.service.ts
Labels: size/XXL, approved

#376 Dev
  .prow/branch-verify.yaml
  .prow/snyk-verify.yaml
  src/app/app.module.ts
  src/app/components/sprint1/users/users.component.html
  src/app/components/sprint1/users/users.component.ts
  src/app/components/sprint3/capital/capital.component.html
  src/app/components/sprint5/add-user-account/add-user-account.component.html
  src/app/components/sprint5/add-user-account/add-user-account.component.ts
  src/app/components/sprint5/approve-loan-request/approve-loan-request.component.css
  src/app/components/sprint5/approve-loan-request/approve-loan-request.component.html
  src/app/components/sprint5/approve-loan-request/approve-loan-request.component.ts
  src/app/components/sprint5/loan-details/loan-details.component.css
  src/app/components/sprint5/loan-details/loan-details.component.html
  src/app/components/sprint5/loan-details/loan-details.component.ts
  src/app/components/sprint5/loan/loan.component.html
  src/app/components/sprint5/loan/loan.component.ts
  src/app/components/sprint5/payments/payments.component.html
  src/app/components/sprint5/payments/payments.component.ts
  src/app/components/sprint5/request-loan/request-loan.component.html
  src/app/components/sprint5/request-loan/request-loan.component.ts
  src/app/services/client.service.ts
  src/app/services/stock.service.ts
Labels: lgtm, size/XXL, approved
