Repository RAF-SI-2022/Banka-2-Frontend, pull requests merged in 2023-05, with the labels that each got.

#211 toastr fix
  src/app/components/app/app.component.ts
  src/app/components/sprint1/add-user/add-user.component.ts
  src/app/components/sprint1/change-password/change-password.component.ts
  src/app/components/sprint1/edit-user/edit-user.component.ts
  src/app/components/sprint1/forgot-password/forgot-password.component.ts
  src/app/components/sprint1/login/login.component.ts
  src/app/components/sprint1/profile/profile.component.ts
  src/app/components/sprint1/users/users.component.ts
  src/app/components/sprint2/forex/forex.component.ts
  src/app/components/sprint2/futures/buy-future-with-limit/buy-future-with-limit.component.ts
  src/app/components/sprint2/futures/futures-component/futures.component.ts
  src/app/components/sprint2/futures/sell-future-with-limit/sell-future-with-limit.component.ts
  src/app/components/sprint2/futures/sell-future/sell-future.component.ts
  src/app/components/sprint2/futures/single-future-table/single-future-table.component.ts
  src/app/components/sprint2/purchases/purchases.component.ts
  src/app/components/sprint2/stocks/buy-stock/buy-stock.component.ts
  src/app/components/sprint2/stocks/sell-stock/sell-stock.component.ts
  src/app/components/sprint2/stocks/stock-details/stock-details.component.ts
  src/app/components/sprint2/stocks/stock-options/stock-options.component.ts
  src/app/components/sprint2/stocks/stock-sell-table/stock-sell-table.component.ts
  src/app/components/sprint2/stocks/stocks-table/stocks.component.ts
  src/app/components/sprint3/capital/capital.component.ts
  src/app/components/sprint3/deposit-withdraw-capital/deposit-withdraw-capital.component.ts
  src/app/components/sprint3/future-contract/future-contract.component.ts
  src/app/components/sprint3/my-stock-options/my-stock-options.component.ts
  src/app/components/sprint3/transaction-list/transaction-list.component.ts
Labels: size/L

#213 Agent limiti i future orderi sredjeni
  src/app/components/sprint1/profile/profile.component.ts
  src/app/components/sprint2/purchases/purchases.component.ts
  src/app/components/sprint3/capital/capital.component.html
  src/app/components/sprint3/capital/capital.component.ts
  src/app/models/users.model.ts
  src/app/services/user-service.service.ts
Labels: size/M

#214 Lista tranzakcija sredjena, i mali bug na kapitalu
  src/app/components/sprint3/capital/capital.component.html
  src/app/components/sprint3/capital/capital.component.ts
  src/app/components/sprint3/deposit-withdraw-capital/deposit-withdraw-capital.component.html
  src/app/components/sprint3/transaction-list/transaction-list.component.html
  src/app/components/sprint3/transaction-list/transaction-list.component.ts
  src/app/models/stock-exchange.model.ts
Labels: size/L

#215 dodate tabele, future-contract, prikaz amount-a u tabelama u capital,…
  src/app/components/sprint3/capital/capital.component.html
  src/app/components/sprint3/capital/capital.component.ts
  src/app/components/sprint3/future-contract/future-contract.component.html
  src/app/components/sprint3/future-contract/future-contract.component.ts
  src/app/services/stock.service.ts
Labels: size/L

#216 neka sitna greska popravljena
  src/app/components/sprint3/capital/capital.component.html
  src/app/components/sprint3/capital/capital.component.ts
Labels: size/XS

#217 fixes and agents tab for supervisor
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/app/app.component.html
  src/app/components/app/app.component.ts
  src/app/components/sprint2/stocks/buy-stock/buy-stock.component.ts
  src/app/components/sprint2/stocks/stock-options/stock-options.component.ts
  src/app/components/sprint2/stocks/stocks-table/stocks.component.ts
  src/app/components/sprint3/agents/agents.component.css
  src/app/components/sprint3/agents/agents.component.html
  src/app/components/sprint3/agents/agents.component.ts
  src/app/components/sprint3/capital/capital.component.ts
  src/app/components/sprint3/change-agent-limit/change-agent-limit.component.css
  src/app/components/sprint3/change-agent-limit/change-agent-limit.component.html
  src/app/components/sprint3/change-agent-limit/change-agent-limit.component.ts
  src/app/components/sprint3/my-stock-options/my-stock-options.component.html
  src/app/services/user-service.service.ts
Labels: size/XL

#218 Added production Docker script, updated Make
  Dockerfile
  Makefile
  docker-compose.yml
  make.bat
  package.json
Labels: size/M

#220 123
  src/app/components/sprint2/purchases/purchases.component.html
  src/app/components/sprint2/purchases/purchases.component.ts
  src/app/components/sprint2/stocks/stock-sell-table/stock-sell-table.component.html
  src/app/components/sprint3/capital/capital.component.ts
  src/app/services/stock.service.ts
Labels: size/M

#221 sklonjena tabela na click future ugovor, update total za akcije
  src/app/components/sprint3/capital/capital.component.ts
  src/app/components/sprint3/future-contract/future-contract.component.html
Labels: size/S

#222 Porudzbine: Agent moze samo da vidi svoje porudzbine
  src/app/components/sprint2/purchases/purchases.component.html
  src/app/components/sprint2/purchases/purchases.component.ts
  src/app/components/sprint2/stocks/stocks-table/stocks.component.html
  src/app/components/sprint3/transaction-list/transaction-list.component.html
  src/app/services/stock.service.ts
Labels: size/L

#225 future limit ispravka kod errora
  src/app/components/sprint2/futures/buy-future-with-limit/buy-future-with-limit.component.ts
Labels: size/S

#227 E2E testovi
  cypress.config.ts
  cypress/e2e/testAddUser.cy.js
  cypress/e2e/testBuyStock.cy.js
  cypress/e2e/testCapital.cy.js
  cypress/e2e/testEditUser.cy.js
  cypress/e2e/testForex.cy.js
  cypress/e2e/testFutureContract.cy.js
  cypress/e2e/testHomePage.cy.js
  cypress/e2e/testSellStock.cy.js
  cypress/e2e/testStockDetails.cy.js
  src/app/components/sprint1/add-user/addUserTestComponents.ts
  src/app/components/sprint1/edit-user/editUserTestComponents.ts
  src/app/components/sprint1/home/homeTestComponents.ts
  src/app/components/sprint1/profile/profileTestComponents.ts
  src/app/components/sprint1/users/usersTestComponents.ts
  src/app/components/sprint2/forex/forexTestComponents.ts
  src/app/components/sprint2/stocks/buy-stock/buyStockTestComponents.ts
  src/app/components/sprint2/stocks/sell-stock/sellStockTestComponents.ts
  src/app/components/sprint2/stocks/stock-details/stockDetailsTestComponents.ts
  src/app/components/sprint3/capital/capitalTestComponents.ts
  src/app/components/sprint3/future-contract/futureContractTestComponents.ts
Labels: size/XL

#232 Sprint3
  cypress.config.ts
  cypress/e2e/testAddUser.cy.js
  cypress/e2e/testBuyStock.cy.js
  cypress/e2e/testCapital.cy.js
  cypress/e2e/testEditUser.cy.js
  cypress/e2e/testForex.cy.js
  cypress/e2e/testFutureContract.cy.js
  cypress/e2e/testHomePage.cy.js
  cypress/e2e/testSellStock.cy.js
  cypress/e2e/testStockDetails.cy.js
  src/app/components/sprint1/add-user/addUserTestComponents.ts
  src/app/components/sprint1/edit-user/editUserTestComponents.ts
  src/app/components/sprint1/home/homeTestComponents.ts
  src/app/components/sprint1/profile/profileTestComponents.ts
  src/app/components/sprint1/users/usersTestComponents.ts
  src/app/components/sprint2/forex/forexTestComponents.ts
  src/app/components/sprint2/stocks/buy-stock/buyStockTestComponents.ts
  src/app/components/sprint2/stocks/sell-stock/sellStockTestComponents.ts
  src/app/components/sprint2/stocks/stock-details/stockDetailsTestComponents.ts
  src/app/components/sprint3/capital/capitalTestComponents.ts
  src/app/components/sprint3/future-contract/futureContractTestComponents.ts
Labels: size/XL

#233 Add company and create company pages, awaiting backend integration
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/sprint4/companies/companies.component.css
  src/app/components/sprint4/companies/companies.component.html
  src/app/components/sprint4/companies/companies.component.spec.ts
  src/app/components/sprint4/companies/companies.component.ts
  src/app/components/sprint4/company-details/company-details.component.css
  src/app/components/sprint4/company-details/company-details.component.html
  src/app/components/sprint4/company-details/company-details.component.spec.ts
  src/app/components/sprint4/company-details/company-details.component.ts
  src/app/components/sprint4/create-company/create-company.component.css
  src/app/components/sprint4/create-company/create-company.component.html
  src/app/components/sprint4/create-company/create-company.component.spec.ts
  src/app/components/sprint4/create-company/create-company.component.ts
  src/app/models/stock-exchange.model.ts
Labels: size/XXL

#235 add of folders
  cypress/e2e/capitalTests/testCapital.cy.js
  cypress/e2e/forexTests/testForex.cy.js
  cypress/e2e/futuresTests/testFutureContract.cy.js
  cypress/e2e/homeTests/testHomePage.cy.js
  cypress/e2e/loginTests/testLogin.cy.js
  cypress/e2e/profileTests/testProfile.cy.js
  cypress/e2e/stockTests/testBuyStock.cy.js
  cypress/e2e/stockTests/testSellStock.cy.js
  cypress/e2e/stockTests/testStockDetails.cy.js
  cypress/e2e/userTests/testAddUser.cy.js
  cypress/e2e/userTests/testEditUser.cy.js
  cypress/e2e/userTests/testUsers.cy.js
Labels: size/M

#237 fixes and improvements on some tests
  cypress/e2e/stockTests/testBuyStock.cy.js
  cypress/e2e/stockTests/testSellStock.cy.js
  cypress/e2e/userTests/testAddUser.cy.js
  cypress/e2e/userTests/testEditUser.cy.js
  src/app/components/sprint1/add-user/addUserTestComponents.ts
  src/app/components/sprint1/edit-user/editUserTestComponents.ts
  src/app/components/sprint1/users/users.component.ts
  src/app/components/sprint2/stocks/buy-stock/buy-stock.component.ts
  src/app/components/sprint2/stocks/buy-stock/buyStockTestComponents.ts
  src/app/components/sprint2/stocks/stock-options/stock-options.component.ts
Labels: size/L

#240 Add few tests, fix some bugs
  cypress/e2e/forgotPasswordTests/testForgotPassword.cy.js
  cypress/e2e/futuresTests/testBuyFutureContract.cy.js
  cypress/e2e/futuresTests/testSellFutureContract.cy.js
  cypress/e2e/futuresTests/testSellFutureContractWithLimit.cy.js
  src/app/app-routing.module.ts
  src/app/components/sprint2/stocks/stock-details/stockDetailsTestComponents.ts
  src/app/components/sprint2/stocks/stock-options/stock-options.component.css
  src/app/components/sprint2/stocks/stock-options/stock-options.component.html
  src/app/components/sprint2/stocks/stock-options/stock-options.component.ts
  src/app/components/sprint3/buy-stock-option/buy-stock-option.component.ts
  src/app/components/sprint3/future-contract/futureContractTestComponents.ts
  src/app/components/sprint3/my-stock-options/my-stock-options.component.html
Labels: size/L

#241 Testovi i male prepravke
  cypress/e2e/agentsTests/testAgent.cy.js
  cypress/e2e/capitalTests/testCapital.cy.js
  src/app/components/sprint2/stocks/stock-sell-table/stock-sell-table.component.html
  src/app/components/sprint2/stocks/stock-sell-table/stockSellTableTestComponents.ts
  src/app/components/sprint3/capital/capitalTestComponents.ts
  src/app/components/sprint3/deposit-withdraw-capital/deposit-withdraw-capital.component.html
Labels: size/L

#243 Sprint4
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/sprint3/deposit-withdraw-capital/deposit-withdraw-capital.component.html
  src/app/components/sprint4/companies/companies.component.css
  src/app/components/sprint4/companies/companies.component.spec.ts
  src/app/components/sprint4/company-details/company-details.component.html
  src/app/components/sprint4/company-details/company-details.component.ts
  src/app/components/sprint4/create-company-contract/create-company-contract.component.css
  src/app/components/sprint4/create-company-contract/create-company-contract.component.html
  src/app/components/sprint4/create-company-contract/create-company-contract.component.ts
  src/app/models/stock-exchange.model.ts
  src/app/services/stock.service.ts
Labels: size/L

#244 dodate komponente, unapredjen racun
  src/app/components/sprint4/company-details/company-details.component.html
  src/app/components/sprint4/company-details/company-details.component.spec.ts
  src/app/components/sprint4/company-details/company-details.component.ts
  src/app/components/sprint4/create-company-account/create-company-account.component.css
  src/app/components/sprint4/create-company-account/create-company-account.component.html
  src/app/components/sprint4/create-company-account/create-company-account.component.ts
  src/app/components/sprint4/single-account/single-account.component.css
  src/app/components/sprint4/single-account/single-account.component.html
  src/app/components/sprint4/single-account/single-account.component.ts
Labels: size/L

#245 update
  src/app/components/sprint4/company-details/company-details.component.ts
  src/app/components/sprint4/single-contract/single-contract.component.css
  src/app/components/sprint4/single-contract/single-contract.component.html
  src/app/components/sprint4/single-contract/single-contract.component.ts
Labels: size/L

#246 update za contracts
  src/app/services/contract.service.ts
Labels: size/S

#247 Nisu se povukli svi fajlovi u prethodnom pull requestu
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/app/app.component.html
  src/app/components/sprint4/company-details/company-details.component.html
  src/app/components/sprint4/company-details/company-details.component.ts
  src/app/components/sprint4/single-contract/single-contract.component.html
  src/app/components/sprint4/single-contract/single-contract.component.ts
  src/index.html
  src/styles.css
Labels: size/L
